spring:
  application:
    name: hackathon
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health

jwt:
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}